# Uncomment the next line to define a global platform for your project
 platform :ios, '11.2'

target 'ChatApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'Socket.IO-Client-Swift', '~> 13.1.0’
pod 'JSQMessagesViewController'
pod 'HandyJSON','~> 4.0.0-beta.1'

end
